### Install and Import Libraries

In [ ]:
!pip install
!pip install mlflow

import pandas as pd
import time
import optuna
import os
import mlflow
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import precision_score, recall_score, classification_report
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

ERROR: You must give at least one requirement to install (see "pip help install")
Collecting mlflow
  Downloading mlflow-3.16.0-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.0/50.0 kB 3.7 MB/s eta 0:00:00
Collecting mlflow-skinny==3.16.0 (from mlflow)
  Downloading mlflow_skinny-3.16.0-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.9/50.9 kB 5.4 MB/s eta 0:00:00
Collecting mlflow-tracing==3.16.0 (from mlflow)
  Downloading mlflow_tracing-3.16.0-py3-none-any.whl.metadata (19 kB)
Collecting Flask-CORS<7 (from mlflow)
  Downloading flask_cors-6.0.5-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: Flask<4 in /usr/local/lib/python3.13/dist-packages (from mlflow) (3.1.3)
Requirement already satisfied: aiohttp<4,>=3.7.0 in /usr/local/lib/python3.13/dist-packages (from mlflow) (3.14.3)
Requirement already satisfied: alembic!=1.10.0,<2 in /usr/local/lib/python3.13/dist-packages (from mlflow) (1.19.2)
Requirement already satisfied: cryptography<51,>=43.0.0 in /usr/local/lib/python3.13/dist-packages (from mlflow) (50.0.1)
Collecting docker<8,>=4.0.0 (from mlflow)
  Downloading docker-7.2.0-py3-none-any.whl.metadata (3.8 kB)
Collecting graphene<4 (from mlflow)
  Downloading graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting gunicorn<27 (from mlflow)
  Downloading gunicorn-26.2.0-py3-none-any.whl.metadata (5.5 kB)
Collecting huey<4,>=2.5.4 (from mlflow)
  Downloading huey-3.4.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: matplotlib<4 in /usr/local/lib/python3.13/dist-packages (from mlflow) (3.10.0)
Requirement already satisfied: numpy<3 in /usr/local/lib/python3.13/dist-packages (from mlflow) (2.1.3)
Requirement already satisfied: pandas<4 in /usr/local/lib/python3.13/dist-packages (from mlflow) (2.2.3)
Requirement already satisfied: pyarrow<26,>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from mlflow) (23.0.1)
Requirement already satisfied: scikit-learn<2 in /usr/local/lib/python3.13/dist-packages (from mlflow) (1.6.1)
Requirement already satisfied: scipy<2 in /usr/local/lib/python3.13/dist-packages (from mlflow) (1.16.3)
Collecting skops<1 (from mlflow)
  Downloading skops-0.14.0-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from mlflow) (2.0.52)
Requirement already satisfied: anyio!=4.15.0,<5,>=3.6.2 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.16.0->mlflow) (4.14.2)
Requirement already satisfied: cachetools<8,>=5.0.0 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.16.0->mlflow) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.16.0->mlflow) (8.5.0)
Requirement already satisfied: cloudpickle<4 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.16.0->mlflow) (3.1.2)
Collecting databricks-sdk<1,>=0.20.0 (from mlflow-skinny==3.16.0->mlflow)
  Downloading databricks_sdk-0.137.0-py3-none-any.whl.metadata (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.2/44.2 kB 5.1 MB/s eta 0:00:00
Requirement already satisfied: fastapi<1 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.16.0->mlflow) (0.141.1)
Collecting gitpython<4,>=3.1.9 (from mlflow-skinny==3.16.0->mlflow)
  Downloading gitpython-3.1.62-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: importlib_metadata!=4.7.0,<10,>=3.7.0 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.16.0->mlflow) (9.0.1)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.16.0->mlflow) (1.42.1)
Collecting opentelemetry-proto<3,>=1.9.0 (from mlflow-skinny==3.16.0->mlflow)
  Downloading opentelemetry_proto-1.44.0-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.16.0->mlflow) (1.42.1)
Requirement already satisfied: packaging<27 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.16.0->mlflow) (26.3)
Requirement already satisfied: protobuf<8,>=3.12.0 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.16.0->mlflow) (5.29.6)
Requirement already satisfied: pydantic<3,>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.16.0->mlflow) (2.13.5)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.16.0->mlflow) (1.2.3)
Requirement already satisfied: pyyaml<7,>=5.1 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.16.0->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.16.0->mlflow) (2.32.4)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.16.0->mlflow) (0.6.0)
Requirement already satisfied: starlette<2 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.16.0->mlflow) (1.6.0)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.16.0->mlflow) (4.16.0)
Requirement already satisfied: uvicorn<1 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.16.0->mlflow) (0.52.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (1.24.5)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic!=1.10.0,<2->mlflow) (1.3.2.dev0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from cryptography<51,>=43.0.0->mlflow) (2.1.1)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from docker<8,>=4.0.0->mlflow) (2.5.0)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.13/dist-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.13/dist-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.13/dist-packages (from Flask<4->mlflow) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from Flask<4->mlflow) (3.1.8)
Collecting graphql-core<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_core-3.2.12-py3-none-any.whl.metadata (11 kB)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in /usr/local/lib/python3.13/dist-packages (from graphene<4->mlflow) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib<4->mlflow) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib<4->mlflow) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib<4->mlflow) (1.5.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib<4->mlflow) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib<4->mlflow) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas<4->mlflow) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas<4->mlflow) (2026.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn<2->mlflow) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn<2->mlflow) (3.6.0)
Requirement already satisfied: prettytable>=3.9 in /usr/local/lib/python3.13/dist-packages (from skops<1->mlflow) (3.18.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.5.5)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.13/dist-packages (from anyio!=4.15.0,<5,>=3.6.2->mlflow-skinny==3.16.0->mlflow) (3.19)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi>=2.0.0->cryptography<51,>=43.0.0->mlflow) (3.0)
Requirement already satisfied: google-auth~=2.0 in /usr/local/lib/python3.13/dist-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.16.0->mlflow) (2.49.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from fastapi<1->mlflow-skinny==3.16.0->mlflow) (0.4.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from fastapi<1->mlflow-skinny==3.16.0->mlflow) (0.0.5)
Collecting gitdb<5,>=4.0.1 (from gitpython<4,>=3.1.9->mlflow-skinny==3.16.0->mlflow)
  Downloading gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.13/dist-packages (from importlib_metadata!=4.7.0,<10,>=3.7.0->mlflow-skinny==3.16.0->mlflow) (4.1.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.63b1 in /usr/local/lib/python3.13/dist-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.16.0->mlflow) (0.63b1)
Requirement already satisfied: wcwidth>=0.3.5 in /usr/local/lib/python3.13/dist-packages (from prettytable>=3.9->skops<1->mlflow) (0.8.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.16.0->mlflow) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.16.0->mlflow) (2.46.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.16.0->mlflow) (3.4.9)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.16.0->mlflow) (2026.7.22)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.13/dist-packages (from uvicorn<1->mlflow-skinny==3.16.0->mlflow) (0.16.0)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.16.0->mlflow)
  Downloading smmap-5.0.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.13/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.16.0->mlflow) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.13/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.16.0->mlflow) (4.9.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.13/dist-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.16.0->mlflow) (0.6.4)
Downloading mlflow-3.16.0-py3-none-any.whl (11.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 118.0 MB/s eta 0:00:00
Downloading mlflow_skinny-3.16.0-py3-none-any.whl (3.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 125.5 MB/s eta 0:00:00
Downloading mlflow_tracing-3.16.0-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 103.5 MB/s eta 0:00:00
Downloading docker-7.2.0-py3-none-any.whl (148 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 148.8/148.8 kB 17.5 MB/s eta 0:00:00
Downloading flask_cors-6.0.5-py3-none-any.whl (16 kB)
Downloading graphene-3.4.3-py2.py3-none-any.whl (114 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 13.4 MB/s eta 0:00:00
Downloading gunicorn-26.2.0-py3-none-any.whl (228 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 228.4/228.4 kB 21.4 MB/s eta 0:00:00
Downloading huey-3.4.0-py3-none-any.whl (136 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 136.5/136.5 kB 14.6 MB/s eta 0:00:00
Downloading skops-0.14.0-py3-none-any.whl (132 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.2/132.2 kB 16.0 MB/s eta 0:00:00
Downloading databricks_sdk-0.137.0-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 73.7 MB/s eta 0:00:00
Downloading gitpython-3.1.62-py3-none-any.whl (222 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 222.8/222.8 kB 25.4 MB/s eta 0:00:00
Downloading graphql_core-3.2.12-py3-none-any.whl (216 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.0/216.0 kB 25.7 MB/s eta 0:00:00
Downloading graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Downloading opentelemetry_proto-1.44.0-py3-none-any.whl (72 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 8.7 MB/s eta 0:00:00
Downloading gitdb-4.0.12-py3-none-any.whl (62 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 7.9 MB/s eta 0:00:00
Downloading smmap-5.0.3-py3-none-any.whl (24 kB)
Installing collected packages: huey, smmap, opentelemetry-proto, gunicorn, graphql-core, graphql-relay, gitdb, docker, skops, graphene, gitpython, Flask-CORS, databricks-sdk, mlflow-tracing, mlflow-skinny, mlflow
Successfully installed Flask-CORS-6.0.5 databricks-sdk-0.137.0 docker-7.2.0 gitdb-4.0.12 gitpython-3.1.62 graphene-3.4.3 graphql-core-3.2.12 graphql-relay-3.2.0 gunicorn-26.2.0 huey-3.4.0 mlflow-3.16.0 mlflow-skinny-3.16.0 mlflow-tracing-3.16.0 opentelemetry-proto-1.44.0 skops-0.14.0 smmap-5.0.3

### Load Data

In [ ]:
df = pd.read_csv("/content/WA_Fn-UseC_-Telco-Customer-Churn.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [ ]:
CATEGORICAL_FEATURES = ['gender', 'SeniorCitizen', 'Partner',
                        'Dependents', 'PhoneService', 'MultipleLines',
                        'InternetService', 'OnlineSecurity', 'OnlineBackup',
                        'DeviceProtection', 'TechSupport', 'StreamingTV',
                        'StreamingMovies', 'Contract', 'PaperlessBilling',
                        'PaymentMethod']
NUMERICAL_FEATURES = ['tenure', 'MonthlyCharges', 'TotalCharges']

In [ ]:
for category in CATEGORICAL_FEATURES:
  print(f"{category}: {df[category].unique()}")

gender: ['Female' 'Male']
SeniorCitizen: [0 1]
Partner: ['Yes' 'No']
Dependents: ['No' 'Yes']
PhoneService: ['No' 'Yes']
MultipleLines: ['No phone service' 'No' 'Yes']
InternetService: ['DSL' 'Fiber optic' 'No']
OnlineSecurity: ['No' 'Yes' 'No internet service']
OnlineBackup: ['Yes' 'No' 'No internet service']
DeviceProtection: ['No' 'Yes' 'No internet service']
TechSupport: ['No' 'Yes' 'No internet service']
StreamingTV: ['No' 'Yes' 'No internet service']
StreamingMovies: ['No' 'Yes' 'No internet service']
Contract: ['Month-to-month' 'One year' 'Two year']
PaperlessBilling: ['Yes' 'No']
PaymentMethod: ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']

In [ ]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [ ]:
df['Churn'].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

### Data Preprocessing

i. Drop columns not relevant to learning

ii. Split dataset into training and test sets, and into inputs and labels

iii. Fill/make provision to fill NA values

iv. Normalise/scale numerical features

v. Encode categorical features. We treat all the categorical features as nominal, as none has a strict order or hierarchy.

In [ ]:
# Drop the customerID column
df = df.drop('customerID', axis=1)

In [ ]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

In [ ]:
# Create training and test sets
X = df.drop('Churn', axis=1)
y = df['Churn']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=42, stratify=y)

In [ ]:
# Create validation set
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.15, random_state=42, stratify=y_train)

In [ ]:
# Scale numerical features and fill null values
numerical_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

In [ ]:
# Encode categorical features and fill null values
categorical_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

In [ ]:
# Create processing pipeline
processor = ColumnTransformer([
    ('numerical', numerical_pipeline, NUMERICAL_FEATURES),
    ('categorical', categorical_pipeline, CATEGORICAL_FEATURES)
])

### Data Transformation

In [ ]:
X_train = processor.fit_transform(X_train)
X_val = processor.transform(X_val)
X_test = processor.transform(X_test)

In [ ]:
X_train.shape, X_val.shape, X_test.shape

((5088, 46), (898, 46), (1057, 46))

In [ ]:
TARGET_MAPPING = {
    "No": 0,
    "Yes": 1
}
y_train = y_train.map(TARGET_MAPPING)
y_val = y_val.map(TARGET_MAPPING)
y_test = y_test.map(TARGET_MAPPING)

In [ ]:
y_train[:5]

3001    0
2865    0
2715    0
6799    0
6788    0
Name: Churn, dtype: int64

### Model Training

Criteria for choosing models to try out before choosing a final model.

i. It's a classification problem, so we'd train suitable for classification

ii. As a base model, we'd train a Logistic Regression model.

iii. For this problem, interpretability isn't really needed. So we'd train and compare performances of Boosted Tree algorithms - Random Forest, XGBoost and LightGBM

Considering the business context, Churn Prediction is asymmetric in cost. False Negatives (missed churners) cost more than False Positives (loyal customers predicted as churners).
False Positives still has cost, however, so we would not simply optimise for a high recall.

We assume that the business cost of missing a churner is 6 times more than that of targeting a loyal customer.
So for our evaluation metric, we would define a function that models the business cost.

In [ ]:
# When consider which model to choose after training a few options, consider your preferred metrics as well as training and inference time.

Evaluation Metric

In [ ]:
def business_cost(y_true, y_pred, precision_threshold=0.45, penalty_severity=5000):
    # Confusion matrix components
    tp = sum((y_true == 1) & (y_pred == 1))
    fp = sum((y_true == 0) & (y_pred == 1))
    fn = sum((y_true == 1) & (y_pred == 0))

    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0

    # Base cost (6.0x for FN, 1.0x for FP)
    base_cost = (6.0 * fn) + (1.0 * fp)

    # Bottleneck penalty if precision falls below threshold
    penalty = max(0.0, precision_threshold - precision) * penalty_severity

    return base_cost + penalty

Baseline Model

In [ ]:
# Logistic Regression
logistic_reg = LogisticRegression(random_state=42)

start_train = time.time()
logistic_reg.fit(X_train, y_train)
print(f"Training time: {(time.time() - start_train):.2f} seconds")

Training time: 0.05 seconds

In [ ]:
start_pred = time.time()
y_pred = logistic_reg.predict(X_val)
print(f"Prediction time: {(time.time() - start_pred):.2f} seconds")
print(f"Cost: {business_cost(y_val, y_pred)}\n")
print(classification_report(y_val, y_pred))

Prediction time: 0.00 seconds
Cost: 753.0

              precision    recall  f1-score   support

           0       0.84      0.90      0.87       660
           1       0.64      0.52      0.58       238

    accuracy                           0.80       898
   macro avg       0.74      0.71      0.72       898
weighted avg       0.79      0.80      0.79       898

In [ ]:
# Reduce prediction threshold for a higher recall (to capture more churners)
for threshold in [0.15, 0.2, 0.25, 0.3, 0.35, 0.4]:
  y_pred = logistic_reg.predict_proba(X_val)[:,1] > threshold
  print(f"Threshold: {threshold}")
  print(f"Precision: {precision_score(y_val, y_pred, pos_label=1)}")
  print(f"Recall: {recall_score(y_val, y_pred, pos_label=1)}")
  print(f"Cost: {business_cost(y_val, y_pred)}")
  print("\n")

Threshold: 0.15
Precision: 0.433264887063655
Recall: 0.8865546218487395
Cost: 521.675564681725


Threshold: 0.2
Precision: 0.4679334916864608
Recall: 0.8277310924369747
Cost: 470.0


Threshold: 0.25
Precision: 0.49736842105263157
Recall: 0.7941176470588235
Cost: 485.0


Threshold: 0.3
Precision: 0.5438066465256798
Recall: 0.7563025210084033
Cost: 499.0


Threshold: 0.35
Precision: 0.5694915254237288
Recall: 0.7058823529411765
Cost: 547.0


Threshold: 0.4
Precision: 0.5823754789272031
Recall: 0.6386554621848739
Cost: 625.0

In [ ]:
# Based on further exploration, a threshold of 0.3 gives the lowest cost
THRESHOLD = 0.3

More complex models for better performance

Random Forest

In [ ]:
# Random forest classifier
random_forest = RandomForestClassifier(random_state=42, class_weight='balanced')

start_train = time.time()
random_forest.fit(X_train, y_train)
print(f"Training time: {(time.time() - start_train):.2f} seconds")

Training time: 0.65 seconds

In [ ]:
# Make prediction and evaluate model
start_time = time.time()
y_pred = random_forest.predict_proba(X_val)[:,1] > THRESHOLD
print(f"Prediction time: {(time.time() - start_time):.2f} seconds")
print(f"Cost: {business_cost(y_val, y_pred)}\n")
print(classification_report(y_val, y_pred))

Prediction time: 0.02 seconds
Cost: 572.0

              precision    recall  f1-score   support

           0       0.88      0.78      0.83       660
           1       0.53      0.70      0.61       238

    accuracy                           0.76       898
   macro avg       0.71      0.74      0.72       898
weighted avg       0.79      0.76      0.77       898

At a threshold of 0.3, the random forest classifier seems to perform worse than the base model.

LightGBM

In [ ]:
lightgbm = LGBMClassifier(random_state=42, class_weight='balanced')

start_train = time.time()
lightgbm.fit(X_train, y_train)
print(f"Training time: {(time.time() - start_train):.2f} seconds")
print(f"\nModel Parameters: {lightgbm.get_params()}")

[LightGBM] [Info] Number of positive: 1351, number of negative: 3737
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000837 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 670
[LightGBM] [Info] Number of data points in the train set: 5088, number of used features: 46
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
[LightGBM] [Info] Start training from score 0.000000
Training time: 0.18 seconds

Model Parameters: {'boosting_type': 'gbdt', 'class_weight': 'balanced', 'colsample_bytree': 1.0, 'importance_type': 'split', 'learning_rate': 0.1, 'max_depth': -1, 'min_child_samples': 20, 'min_child_weight': 0.001, 'min_split_gain': 0.0, 'n_estimators': 100, 'n_jobs': None, 'num_leaves': 31, 'objective': None, 'random_state': 42, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'subsample': 1.0, 'subsample_for_bin': 200000, 'subsample_freq': 0}

In [ ]:
start_time = time.time()
y_pred = lightgbm.predict_proba(X_val)[:,1] > THRESHOLD
print(f"Prediction time: {(time.time() - start_time):.2f} seconds")
print(f"Cost: {business_cost(y_val, y_pred)}\n")
print(classification_report(y_val, y_pred))

Prediction time: 0.01 seconds
Cost: 450.0

              precision    recall  f1-score   support

           0       0.92      0.64      0.75       660
           1       0.46      0.85      0.60       238

    accuracy                           0.69       898
   macro avg       0.69      0.74      0.67       898
weighted avg       0.80      0.69      0.71       898

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

The LightGBM model achieved a lower cost than the base model and the random forest classifier

XGBoost

In [ ]:
# Calculate scale_pos_weight for imbalance
scale_pos_weight = (y_train == 0).sum() / (y_train == 1).sum()

xgboost = XGBClassifier(random_state=42, scale_pos_weight=scale_pos_weight)

start_train = time.time()
xgboost.fit(X_train, y_train)
print(f"Training time: {(time.time() - start_train):.2f} seconds")

Training time: 0.49 seconds

In [ ]:
start_time = time.time()
y_pred = xgboost.predict_proba(X_val)[:,1] > THRESHOLD
print(f"Prediction time: {(time.time() - start_time):.2f} seconds")
print(f"Cost: {business_cost(y_val, y_pred)}\n")
print(classification_report(y_val, y_pred))

Prediction time: 0.01 seconds
Cost: 522.0

              precision    recall  f1-score   support

           0       0.90      0.69      0.78       660
           1       0.48      0.78      0.59       238

    accuracy                           0.71       898
   macro avg       0.69      0.73      0.69       898
weighted avg       0.78      0.71      0.73       898

XGBoost achieved a cost of 522.

### Hyperparameter Tuning

LightGBM

In [ ]:
def objective(trial):
    # Suggest hyperparameter values
    params = {
        'objective': None,
        'metric': 'binary_logloss',
        'boosting_type': 'gbdt',
        'class_weight': 'balanced',
        'n_estimators': trial.suggest_int('n_estimators', 50, 200),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.2, log=True),
        'num_leaves': trial.suggest_int('num_leaves', 15, 100),
        'max_depth': trial.suggest_int('max_depth', 3, 12),
        'feature_fraction': trial.suggest_float('feature_fraction', 0.4, 1.0),
        'bagging_fraction': trial.suggest_float('bagging_fraction', 0.4, 1.0),
        'bagging_freq': trial.suggest_int('bagging_freq', 1, 7),
        'min_child_samples': trial.suggest_int('min_child_samples', 5, 100),
        'verbose': -1
    }

    # Train and evaluate model
    model = LGBMClassifier(**params)
    model.fit(X_train, y_train)
    y_pred = model.predict_proba(X_val)[:,1] > THRESHOLD

    return business_cost(y_val, y_pred)

In [ ]:
# Create a study object and minimize the objective function
study = optuna.create_study(direction='minimize')
study.optimize(objective, n_trials=30)

print("\nBest trial score (Cost):", study.best_value)

[I 2026-09-09 21:21:13,481] A new study created in memory with name: no-name-0d405894-ce84-4921-ba97-d3d2fe8c2827
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
[I 2026-09-09 21:21:13,661] Trial 0 finished with value: 642.3076923076925 and parameters: {'n_estimators': 141, 'learning_rate': 0.02084972835803554, 'num_leaves': 100, 'max_depth': 3, 'feature_fraction': 0.9508959519893887, 'bagging_fraction': 0.7529958656416864, 'bagging_freq': 7, 'min_child_samples': 33}. Best is trial 0 with value: 642.3076923076925.
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
[I 2026-09-09 21:21:14,033] Trial 1 finished with value: 678.2125693160814 and parameters: {'n_estimators': 131, 'learning_rate': 0.012316137405018015, 'num_leaves': 82, 'max_depth': 12, 'feature_fraction': 0.9830328761243387, 'bagging_fraction': 0.7029148787892501, 'bagging_freq': 2, 'min_child_samples': 82}. Best is trial 0 with value: 642.3076923076925.
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
[I 2026-09-09 21:21:14,450] Trial 2 finished with value: 470.0 and parameters: {'n_estimators': 180, 'learning_rate': 0.075777702432383, 'num_leaves': 34, 'max_depth': 12, 'feature_fraction': 0.8934929826699154, 'bagging_fraction': 0.703095598999559, 'bagging_freq': 3, 'min_child_samples': 20}. Best is trial 2 with value: 470.0.
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
[I 2026-09-09 21:21:14,821] Trial 3 finished with value: 560.5071283095723 and parameters: {'n_estimators': 104, 'learning_rate': 0.02774753080335794, 'num_leaves': 75, 'max_depth': 10, 'feature_fraction': 0.9126770943071836, 'bagging_fraction': 0.9756616647146197, 'bagging_freq': 2, 'min_child_samples': 86}. Best is trial 2 with value: 470.0.
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
[I 2026-09-09 21:21:15,089] Trial 4 finished with value: 528.0515463917526 and parameters: {'n_estimators': 180, 'learning_rate': 0.04323936065754214, 'num_leaves': 94, 'max_depth': 3, 'feature_fraction': 0.8727320369164737, 'bagging_fraction': 0.5307922057838477, 'bagging_freq': 2, 'min_child_samples': 63}. Best is trial 2 with value: 470.0.
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
[I 2026-09-09 21:21:15,466] Trial 5 finished with value: 557.0000000000001 and parameters: {'n_estimators': 138, 'learning_rate': 0.018028032971892278, 'num_leaves': 89, 'max_depth': 6, 'feature_fraction': 0.6331270092729657, 'bagging_fraction': 0.7578172824606941, 'bagging_freq': 3, 'min_child_samples': 80}. Best is trial 2 with value: 470.0.
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
[I 2026-09-09 21:21:15,602] Trial 6 finished with value: 504.20779220779235 and parameters: {'n_estimators': 57, 'learning_rate': 0.1726926457924994, 'num_leaves': 65, 'max_depth': 7, 'feature_fraction': 0.8519059322400608, 'bagging_fraction': 0.4458477515257761, 'bagging_freq': 7, 'min_child_samples': 70}. Best is trial 2 with value: 470.0.
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
[I 2026-09-09 21:21:15,874] Trial 7 finished with value: 450.09401709401703 and parameters: {'n_estimators': 101, 'learning_rate': 0.053918272981246185, 'num_leaves': 89, 'max_depth': 8, 'feature_fraction': 0.8811477615834592, 'bagging_fraction': 0.8274984196492132, 'bagging_freq': 7, 'min_child_samples': 84}. Best is trial 7 with value: 450.09401709401703.
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
[I 2026-09-09 21:21:16,169] Trial 8 finished with value: 462.3965517241379 and parameters: {'n_estimators': 185, 'learning_rate': 0.0697680811721709, 'num_leaves': 73, 'max_depth': 5, 'feature_fraction': 0.5172856836327018, 'bagging_fraction': 0.7318142773032363, 'bagging_freq': 1, 'min_child_samples': 79}. Best is trial 7 with value: 450.09401709401703.
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
[I 2026-09-09 21:21:16,516] Trial 9 finished with value: 525.7966101694916 and parameters: {'n_estimators': 81, 'learning_rate': 0.18578072916149846, 'num_leaves': 83, 'max_depth': 4, 'feature_fraction': 0.9389880065713874, 'bagging_fraction': 0.721621170134511, 'bagging_freq': 2, 'min_child_samples': 95}. Best is trial 7 with value: 450.09401709401703.
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
[I 2026-09-09 21:21:17,009] Trial 10 finished with value: 551.7908902691511 and parameters: {'n_estimators': 85, 'learning_rate': 0.060614974594674506, 'num_leaves': 85, 'max_depth': 4, 'feature_fraction': 0.79598949495069, 'bagging_fraction': 0.7817632713455236, 'bagging_freq': 6, 'min_child_samples': 55}. Best is trial 7 with value: 450.09401709401703.
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
[I 2026-09-09 21:21:17,945] Trial 11 finished with value: 474.377969762419 and parameters: {'n_estimators': 193, 'learning_rate': 0.041289652986737875, 'num_leaves': 76, 'max_depth': 6, 'feature_fraction': 0.5418785467030702, 'bagging_fraction': 0.8245207596654174, 'bagging_freq': 7, 'min_child_samples': 63}. Best is trial 7 with value: 450.09401709401703.
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
[I 2026-09-09 21:21:18,807] Trial 12 finished with value: 512.3716075156576 and parameters: {'n_estimators': 155, 'learning_rate': 0.049300591253208396, 'num_leaves': 63, 'max_depth': 5, 'feature_fraction': 0.6504565412178631, 'bagging_fraction': 0.8166844978767801, 'bagging_freq': 4, 'min_child_samples': 100}. Best is trial 7 with value: 450.09401709401703.
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
[I 2026-09-09 21:21:19,503] Trial 13 finished with value: 497.43254817987156 and parameters: {'n_estimators': 188, 'learning_rate': 0.057044943202405836, 'num_leaves': 81, 'max_depth': 6, 'feature_fraction': 0.4264512872560289, 'bagging_fraction': 0.7388659971335337, 'bagging_freq': 3, 'min_child_samples': 76}. Best is trial 7 with value: 450.09401709401703.
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
[I 2026-09-09 21:21:19,889] Trial 14 finished with value: 474.73913043478274 and parameters: {'n_estimators': 165, 'learning_rate': 0.11114991540979999, 'num_leaves': 61, 'max_depth': 5, 'feature_fraction': 0.7544858552503132, 'bagging_fraction': 0.6917881834387937, 'bagging_freq': 6, 'min_child_samples': 84}. Best is trial 7 with value: 450.09401709401703.
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
[I 2026-09-09 21:21:20,152] Trial 15 finished with value: 466.81012658227866 and parameters: {'n_estimators': 61, 'learning_rate': 0.0799163015194716, 'num_leaves': 88, 'max_depth': 7, 'feature_fraction': 0.9912823358570054, 'bagging_fraction': 0.9316502885637653, 'bagging_freq': 4, 'min_child_samples': 81}. Best is trial 7 with value: 450.09401709401703.
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
[I 2026-09-09 21:21:20,450] Trial 16 finished with value: 541.7280334728034 and parameters: {'n_estimators': 80, 'learning_rate': 0.04117694437679361, 'num_leaves': 86, 'max_depth': 8, 'feature_fraction': 0.4911535702944162, 'bagging_fraction': 0.9083508781519204, 'bagging_freq': 5, 'min_child_samples': 86}. Best is trial 7 with value: 450.09401709401703.
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
[I 2026-09-09 21:21:20,756] Trial 17 finished with value: 515.7241379310345 and parameters: {'n_estimators': 66, 'learning_rate': 0.0727840837320459, 'num_leaves': 85, 'max_depth': 12, 'feature_fraction': 0.8967825694233293, 'bagging_fraction': 0.8300518147611392, 'bagging_freq': 7, 'min_child_samples': 64}. Best is trial 7 with value: 450.09401709401703.
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
[I 2026-09-09 21:21:21,195] Trial 18 finished with value: 501.2243186582811 and parameters: {'n_estimators': 116, 'learning_rate': 0.034859669134106264, 'num_leaves': 86, 'max_depth': 7, 'feature_fraction': 0.7971374681631621, 'bagging_fraction': 0.8539923024418139, 'bagging_freq': 6, 'min_child_samples': 87}. Best is trial 7 with value: 450.09401709401703.
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
[I 2026-09-09 21:21:21,648] Trial 19 finished with value: 422.0 and parameters: {'n_estimators': 97, 'learning_rate': 0.06503170843772528, 'num_leaves': 90, 'max_depth': 9, 'feature_fraction': 0.6961977804380988, 'bagging_fraction': 0.8448930051896469, 'bagging_freq': 3, 'min_child_samples': 65}. Best is trial 19 with value: 422.0.
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
[I 2026-09-09 21:21:22,006] Trial 20 finished with value: 534.6768558951965 and parameters: {'n_estimators': 88, 'learning_rate': 0.09852203707858043, 'num_leaves': 89, 'max_depth': 9, 'feature_fraction': 0.924027154654686, 'bagging_fraction': 0.733255157021854, 'bagging_freq': 7, 'min_child_samples': 94}. Best is trial 19 with value: 422.0.
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
[I 2026-09-09 21:21:22,631] Trial 21 finished with value: 441.0 and parameters: {'n_estimators': 95, 'learning_rate': 0.06494262543371725, 'num_leaves': 87, 'max_depth': 10, 'feature_fraction': 0.9033490382837419, 'bagging_fraction': 0.773313827555373, 'bagging_freq': 5, 'min_child_samples': 55}. Best is trial 19 with value: 422.0.
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
[I 2026-09-09 21:21:23,060] Trial 22 finished with value: 457.3039647577093 and parameters: {'n_estimators': 92, 'learning_rate': 0.05752010395618723, 'num_leaves': 80, 'max_depth': 11, 'feature_fraction': 0.8124022510575926, 'bagging_fraction': 0.7352705120933103, 'bagging_freq': 3, 'min_child_samples': 38}. Best is trial 19 with value: 422.0.
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
[I 2026-09-09 21:21:23,328] Trial 23 finished with value: 490.61016949152554 and parameters: {'n_estimators': 66, 'learning_rate': 0.09048417834008841, 'num_leaves': 88, 'max_depth': 8, 'feature_fraction': 0.674240825284208, 'bagging_fraction': 0.8806283471843377, 'bagging_freq': 7, 'min_child_samples': 81}. Best is trial 19 with value: 422.0.
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
[I 2026-09-09 21:21:23,823] Trial 24 finished with value: 475.0 and parameters: {'n_estimators': 77, 'learning_rate': 0.08850472640633672, 'num_leaves': 84, 'max_depth': 10, 'feature_fraction': 0.9863163413995861, 'bagging_fraction': 0.7631228624209224, 'bagging_freq': 7, 'min_child_samples': 51}. Best is trial 19 with value: 422.0.
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
[I 2026-09-09 21:21:24,246] Trial 25 finished with value: 472.0 and parameters: {'n_estimators': 87, 'learning_rate': 0.08903788366452163, 'num_leaves': 100, 'max_depth': 10, 'feature_fraction': 0.8063227833487328, 'bagging_fraction': 0.8267504106687424, 'bagging_freq': 5, 'min_child_samples': 50}. Best is trial 19 with value: 422.0.
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
[I 2026-09-09 21:21:24,662] Trial 26 finished with value: 484.932059447983 and parameters: {'n_estimators': 97, 'learning_rate': 0.05406065631540498, 'num_leaves': 95, 'max_depth': 7, 'feature_fraction': 0.8443806870425121, 'bagging_fraction': 0.9491539306158678, 'bagging_freq': 6, 'min_child_samples': 81}. Best is trial 19 with value: 422.0.
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
[I 2026-09-09 21:21:25,076] Trial 27 finished with value: 557.2396694214876 and parameters: {'n_estimators': 106, 'learning_rate': 0.030095071651675537, 'num_leaves': 94, 'max_depth': 10, 'feature_fraction': 0.9077067294715455, 'bagging_fraction': 0.7041657959291647, 'bagging_freq': 3, 'min_child_samples': 72}. Best is trial 19 with value: 422.0.
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
[I 2026-09-09 21:21:25,502] Trial 28 finished with value: 487.12280701754395 and parameters: {'n_estimators': 96, 'learning_rate': 0.0671869086777135, 'num_leaves': 88, 'max_depth': 8, 'feature_fraction': 0.9845420328512299, 'bagging_fraction': 0.8927025902242767, 'bagging_freq': 7, 'min_child_samples': 73}. Best is trial 19 with value: 422.0.
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
[I 2026-09-09 21:21:25,744] Trial 29 finished with value: 507.52631578947364 and parameters: {'n_estimators': 59, 'learning_rate': 0.06267410553625086, 'num_leaves': 80, 'max_depth': 8, 'feature_fraction': 0.8694619383279849, 'bagging_fraction': 0.7612456572629464, 'bagging_freq': 6, 'min_child_samples': 77}. Best is trial 19 with value: 422.0.

Best trial score (Cost): 422.0

In [ ]:
# Initialize model with the best parameters from the search
best_params = study.best_params
print(best_params)

model = LGBMClassifier(**best_params)
model.fit(X_train, y_train)
y_pred = model.predict_proba(X_val)[:,1] > THRESHOLD

print(f"Cost: {business_cost(y_val, y_pred)}\n")
print(classification_report(y_val, y_pred))

{'n_estimators': 97, 'learning_rate': 0.06503170843772528, 'num_leaves': 90, 'max_depth': 9, 'feature_fraction': 0.6961977804380988, 'bagging_fraction': 0.8448930051896469, 'bagging_freq': 3, 'min_child_samples': 65}
Cost: 537.0

              precision    recall  f1-score   support

           0       0.89      0.77      0.82       660
           1       0.53      0.73      0.62       238

    accuracy                           0.76       898
   macro avg       0.71      0.75      0.72       898
weighted avg       0.79      0.76      0.77       898

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

XGBoost

In [ ]:
def objective(trial):
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 300, 800),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.2),
        "max_depth": trial.suggest_int("max_depth", 3, 10),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 10),
        "gamma": trial.suggest_float("gamma", 0, 5),
        "reg_alpha": trial.suggest_float("reg_alpha", 0, 5),
        "reg_lambda": trial.suggest_float("reg_lambda", 0, 5),
        "random_state": 42,
        "n_jobs": -1,
        "scale_pos_weight": (y_train == 0).sum() / (y_train == 1).sum(),
        "eval_metric": "logloss"
    }

    model = XGBClassifier(**params)
    model.fit(X_train, y_train)
    proba = model.predict_proba(X_val)[:,1]
    y_pred = (proba >= THRESHOLD).astype(int)
    return business_cost(y_val, y_pred)

In [ ]:
# Run Optuna
study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=30)

print("Best Params:", study.best_params)
print("Best Cost:", study.best_value)

[I 2026-09-09 21:26:08,552] A new study created in memory with name: no-name-160f126e-1565-42d8-b780-02f235eeed2a
[I 2026-09-09 21:26:08,996] Trial 0 finished with value: 473.51599147121533 and parameters: {'n_estimators': 536, 'learning_rate': 0.037018829892997526, 'max_depth': 7, 'subsample': 0.7021305326552456, 'colsample_bytree': 0.62350117309638, 'min_child_weight': 8, 'gamma': 2.2095630851453185, 'reg_alpha': 1.894588373049103, 'reg_lambda': 0.9907604211473647}. Best is trial 0 with value: 473.51599147121533.
[I 2026-09-09 21:26:09,419] Trial 1 finished with value: 484.932059447983 and parameters: {'n_estimators': 625, 'learning_rate': 0.028566987971537026, 'max_depth': 10, 'subsample': 0.6210877375376902, 'colsample_bytree': 0.7080957663575247, 'min_child_weight': 3, 'gamma': 4.034482440559756, 'reg_alpha': 3.783440626748929, 'reg_lambda': 3.09525407574956}. Best is trial 0 with value: 473.51599147121533.
[I 2026-09-09 21:26:09,892] Trial 2 finished with value: 480.0 and parameters: {'n_estimators': 727, 'learning_rate': 0.14137246681686672, 'max_depth': 7, 'subsample': 0.9885539590338481, 'colsample_bytree': 0.8075215179419414, 'min_child_weight': 9, 'gamma': 0.15742077411951327, 'reg_alpha': 2.1212826973746606, 'reg_lambda': 4.862017064054623}. Best is trial 0 with value: 473.51599147121533.
[I 2026-09-09 21:26:10,234] Trial 3 finished with value: 491.1769722814498 and parameters: {'n_estimators': 782, 'learning_rate': 0.13711011576965407, 'max_depth': 7, 'subsample': 0.9371671247290534, 'colsample_bytree': 0.7294293997523223, 'min_child_weight': 7, 'gamma': 2.844885018581416, 'reg_alpha': 1.7004012530087693, 'reg_lambda': 2.457039583264228}. Best is trial 0 with value: 473.51599147121533.
[I 2026-09-09 21:26:10,646] Trial 4 finished with value: 479.7259100642398 and parameters: {'n_estimators': 673, 'learning_rate': 0.15661942423357253, 'max_depth': 6, 'subsample': 0.6053696558414805, 'colsample_bytree': 0.8843256186306123, 'min_child_weight': 4, 'gamma': 3.3359887489053297, 'reg_alpha': 2.9461368596126123, 'reg_lambda': 3.762068206950074}. Best is trial 0 with value: 473.51599147121533.
[I 2026-09-09 21:26:11,189] Trial 5 finished with value: 524.2677824267781 and parameters: {'n_estimators': 732, 'learning_rate': 0.018751185944830436, 'max_depth': 3, 'subsample': 0.8261327233818562, 'colsample_bytree': 0.9972892191770056, 'min_child_weight': 6, 'gamma': 1.4931866094153923, 'reg_alpha': 2.2629140329257504, 'reg_lambda': 4.648950775692643}. Best is trial 0 with value: 473.51599147121533.
[I 2026-09-09 21:26:11,698] Trial 6 finished with value: 535.3333333333333 and parameters: {'n_estimators': 565, 'learning_rate': 0.011526301947273053, 'max_depth': 6, 'subsample': 0.9233283481102079, 'colsample_bytree': 0.8923388896929344, 'min_child_weight': 4, 'gamma': 3.9766879955855527, 'reg_alpha': 2.195516547363922, 'reg_lambda': 1.1948096128167751}. Best is trial 0 with value: 473.51599147121533.
[I 2026-09-09 21:26:12,120] Trial 7 finished with value: 528.0515463917526 and parameters: {'n_estimators': 538, 'learning_rate': 0.013681993623733653, 'max_depth': 3, 'subsample': 0.8511376796583451, 'colsample_bytree': 0.7249550833679298, 'min_child_weight': 7, 'gamma': 0.5519305015904374, 'reg_alpha': 4.734655950815656, 'reg_lambda': 4.445795291115699}. Best is trial 0 with value: 473.51599147121533.
[I 2026-09-09 21:26:12,418] Trial 8 finished with value: 462.0192719486083 and parameters: {'n_estimators': 442, 'learning_rate': 0.09268486826904716, 'max_depth': 9, 'subsample': 0.7103288923839282, 'colsample_bytree': 0.8817831015021742, 'min_child_weight': 6, 'gamma': 4.388663694502812, 'reg_alpha': 0.6479765491373773, 'reg_lambda': 3.3651428726380725}. Best is trial 8 with value: 462.0192719486083.
[I 2026-09-09 21:26:12,751] Trial 9 finished with value: 552.75 and parameters: {'n_estimators': 656, 'learning_rate': 0.07506830341896836, 'max_depth': 5, 'subsample': 0.8574049578226413, 'colsample_bytree': 0.6358699337289522, 'min_child_weight': 1, 'gamma': 2.346385883141835, 'reg_alpha': 3.330576943108992, 'reg_lambda': 2.305555082689854}. Best is trial 8 with value: 462.0192719486083.
[I 2026-09-09 21:26:13,149] Trial 10 finished with value: 485.4615384615386 and parameters: {'n_estimators': 577, 'learning_rate': 0.13598662627527847, 'max_depth': 5, 'subsample': 0.5852449760750952, 'colsample_bytree': 0.7414141344779341, 'min_child_weight': 10, 'gamma': 3.9227340643201427, 'reg_alpha': 0.28260096069616386, 'reg_lambda': 3.416029869982592}. Best is trial 8 with value: 462.0192719486083.
[I 2026-09-09 21:26:13,757] Trial 11 finished with value: 454.0 and parameters: {'n_estimators': 649, 'learning_rate': 0.041755878918156256, 'max_depth': 9, 'subsample': 0.6921970122140866, 'colsample_bytree': 0.6061258741714203, 'min_child_weight': 8, 'gamma': 1.5070358273492173, 'reg_alpha': 1.8777314261120177, 'reg_lambda': 0.8771575245543426}. Best is trial 11 with value: 454.0.
[I 2026-09-09 21:26:14,512] Trial 12 finished with value: 421.0 and parameters: {'n_estimators': 785, 'learning_rate': 0.018321864790821, 'max_depth': 9, 'subsample': 0.6823351704322228, 'colsample_bytree': 0.630517177462101, 'min_child_weight': 7, 'gamma': 1.9638909530154491, 'reg_alpha': 2.2621620798134314, 'reg_lambda': 1.3330117513884856}. Best is trial 12 with value: 421.0.
[I 2026-09-09 21:26:15,078] Trial 13 finished with value: 475.31718061674025 and parameters: {'n_estimators': 774, 'learning_rate': 0.07968585274795092, 'max_depth': 8, 'subsample': 0.7097102995021037, 'colsample_bytree': 0.5588080550815117, 'min_child_weight': 7, 'gamma': 1.447908539534759, 'reg_alpha': 3.0122925923496324, 'reg_lambda': 1.5671783901960106}. Best is trial 12 with value: 421.0.
[I 2026-09-09 21:26:17,305] Trial 14 finished with value: 500.50000000000006 and parameters: {'n_estimators': 666, 'learning_rate': 0.011827006995016986, 'max_depth': 9, 'subsample': 0.6970285514101624, 'colsample_bytree': 0.5685363949599476, 'min_child_weight': 7, 'gamma': 2.2771351383981293, 'reg_alpha': 3.217182736766758, 'reg_lambda': 0.9577079850244916}. Best is trial 12 with value: 421.0.
[I 2026-09-09 21:26:18,334] Trial 15 finished with value: 444.0 and parameters: {'n_estimators': 759, 'learning_rate': 0.0300287072139971, 'max_depth': 5, 'subsample': 0.528792184374515, 'colsample_bytree': 0.6358388858022173, 'min_child_weight': 9, 'gamma': 1.3770437083719376, 'reg_alpha': 2.2768652717295823, 'reg_lambda': 0.9718884275744928}. Best is trial 12 with value: 421.0.
[I 2026-09-09 21:26:19,318] Trial 16 finished with value: 430.0 and parameters: {'n_estimators': 798, 'learning_rate': 0.01357729558474394, 'max_depth': 7, 'subsample': 0.6105856168796662, 'colsample_bytree': 0.6476236420269441, 'min_child_weight': 9, 'gamma': 1.3080329773863055, 'reg_alpha': 1.2902319216948208, 'reg_lambda': 1.4897940544543755}. Best is trial 12 with value: 421.0.
[I 2026-09-09 21:26:20,206] Trial 17 finished with value: 453.0 and parameters: {'n_estimators': 779, 'learning_rate': 0.03044222523500495, 'max_depth': 10, 'subsample': 0.5531161045275874, 'colsample_bytree': 0.7291950567058985, 'min_child_weight': 5, 'gamma': 1.7005076290999952, 'reg_alpha': 1.224608426268463, 'reg_lambda': 1.9971908661559628}. Best is trial 12 with value: 421.0.
[I 2026-09-09 21:26:20,900] Trial 18 finished with value: 421.0 and parameters: {'n_estimators': 756, 'learning_rate': 0.03927772290062691, 'max_depth': 9, 'subsample': 0.5999262000929747, 'colsample_bytree': 0.7787346044114175, 'min_child_weight': 10, 'gamma': 2.5533344717149618, 'reg_alpha': 1.233148976318354, 'reg_lambda': 1.3662377176770408}. Best is trial 12 with value: 421.0.
[I 2026-09-09 21:26:21,456] Trial 19 finished with value: 456.2403433476394 and parameters: {'n_estimators': 742, 'learning_rate': 0.022964188444414384, 'max_depth': 8, 'subsample': 0.7919837080771939, 'colsample_bytree': 0.5447945272886277, 'min_child_weight': 6, 'gamma': 2.52988490674241, 'reg_alpha': 1.3720642983066291, 'reg_lambda': 1.0639889933600883}. Best is trial 12 with value: 421.0.
[I 2026-09-09 21:26:22,418] Trial 20 finished with value: 470.0 and parameters: {'n_estimators': 775, 'learning_rate': 0.02236746058613616, 'max_depth': 10, 'subsample': 0.571841067673528, 'colsample_bytree': 0.8807936298534954, 'min_child_weight': 6, 'gamma': 1.949433260694601, 'reg_alpha': 0.9869695964795686, 'reg_lambda': 0.8869217092838227}. Best is trial 12 with value: 421.0.
[I 2026-09-09 21:26:23,290] Trial 21 finished with value: 458.0 and parameters: {'n_estimators': 719, 'learning_rate': 0.033778857262685695, 'max_depth': 8, 'subsample': 0.6565100640766733, 'colsample_bytree': 0.5382034315389135, 'min_child_weight': 7, 'gamma': 0.5961470661101304, 'reg_alpha': 2.192290395164686, 'reg_lambda': 2.2966991715420795}. Best is trial 12 with value: 421.0.
[I 2026-09-09 21:26:24,088] Trial 22 finished with value: 435.0 and parameters: {'n_estimators': 742, 'learning_rate': 0.02505360906811059, 'max_depth': 9, 'subsample': 0.6231211690892824, 'colsample_bytree': 0.7787637899240171, 'min_child_weight': 9, 'gamma': 2.1795141227804744, 'reg_alpha': 0.5964107635124952, 'reg_lambda': 2.6101220594160495}. Best is trial 12 with value: 421.0.
[I 2026-09-09 21:26:25,178] Trial 23 finished with value: 442.0 and parameters: {'n_estimators': 796, 'learning_rate': 0.011285195342387838, 'max_depth': 10, 'subsample': 0.5123858253613573, 'colsample_bytree': 0.6303216068636005, 'min_child_weight': 10, 'gamma': 1.2759900717472834, 'reg_alpha': 0.354939610216374, 'reg_lambda': 1.64567823618887}. Best is trial 12 with value: 421.0.
[I 2026-09-09 21:26:25,837] Trial 24 finished with value: 440.0 and parameters: {'n_estimators': 767, 'learning_rate': 0.03176115305735315, 'max_depth': 9, 'subsample': 0.6384456746193476, 'colsample_bytree': 0.8437094374167279, 'min_child_weight': 10, 'gamma': 2.4917284049673527, 'reg_alpha': 1.9400094040587677, 'reg_lambda': 0.8870344118430138}. Best is trial 12 with value: 421.0.
[I 2026-09-09 21:26:26,635] Trial 25 finished with value: 427.0 and parameters: {'n_estimators': 776, 'learning_rate': 0.01441676325794948, 'max_depth': 7, 'subsample': 0.56477957296572, 'colsample_bytree': 0.6581395642132534, 'min_child_weight': 8, 'gamma': 2.483326054452914, 'reg_alpha': 1.3871775394500068, 'reg_lambda': 0.786503350950327}. Best is trial 12 with value: 421.0.
[I 2026-09-09 21:26:27,221] Trial 26 finished with value: 473.0169491525425 and parameters: {'n_estimators': 775, 'learning_rate': 0.02637813909586554, 'max_depth': 9, 'subsample': 0.579710213047817, 'colsample_bytree': 0.7195556820738145, 'min_child_weight': 9, 'gamma': 3.206117172392505, 'reg_alpha': 2.2303156103110684, 'reg_lambda': 1.800241199618739}. Best is trial 12 with value: 421.0.
[I 2026-09-09 21:26:29,891] Trial 27 finished with value: 434.0 and parameters: {'n_estimators': 772, 'learning_rate': 0.012097809492338227, 'max_depth': 9, 'subsample': 0.5285434541668145, 'colsample_bytree': 0.7575989692028925, 'min_child_weight': 10, 'gamma': 1.7878594007693842, 'reg_alpha': 1.4577961231952945, 'reg_lambda': 1.5754146560205835}. Best is trial 12 with value: 421.0.
[I 2026-09-09 21:26:30,781] Trial 28 finished with value: 455.8550106609808 and parameters: {'n_estimators': 787, 'learning_rate': 0.017193511308981217, 'max_depth': 10, 'subsample': 0.6205368112086506, 'colsample_bytree': 0.6313576012369064, 'min_child_weight': 7, 'gamma': 2.785115524770559, 'reg_alpha': 1.6152246207499013, 'reg_lambda': 1.0345366160890075}. Best is trial 12 with value: 421.0.
[I 2026-09-09 21:26:31,368] Trial 29 finished with value: 444.62068965517244 and parameters: {'n_estimators': 793, 'learning_rate': 0.030004807743836227, 'max_depth': 8, 'subsample': 0.5886953176185262, 'colsample_bytree': 0.5382228636743818, 'min_child_weight': 8, 'gamma': 2.7919354310767117, 'reg_alpha': 1.6644237713822445, 'reg_lambda': 1.0054686555247938}. Best is trial 12 with value: 421.0.

Best Params: {'n_estimators': 785, 'learning_rate': 0.018321864790821, 'max_depth': 9, 'subsample': 0.6823351704322228, 'colsample_bytree': 0.630517177462101, 'min_child_weight': 7, 'gamma': 1.9638909530154491, 'reg_alpha': 2.2621620798134314, 'reg_lambda': 1.3330117513884856}
Best Cost: 421.0

In [ ]:
scale_pos_weight = (y_train == 0).sum() / (y_train == 1).sum()

# Add the scale_pos_weight and fixed params to the best ones from Optuna
best_params = study.best_params
best_params.update({
    "random_state": 42,
    "n_jobs": -1,
    "scale_pos_weight": scale_pos_weight,
    "eval_metric": "logloss"
})

# Create model from best params
xgb = XGBClassifier(**best_params)
xgb.fit(X_train, y_train)

proba = xgb.predict_proba(X_val)[:,1]
y_pred = (proba >= THRESHOLD).astype(int)

# Classification report
print(f"Cost: {business_cost(y_val, y_pred)}\n")
print(classification_report(y_val, y_pred, digits=3))

Cost: 421.0

              precision    recall  f1-score   support

           0      0.936     0.617     0.743       660
           1      0.454     0.882     0.599       238

    accuracy                          0.687       898
   macro avg      0.695     0.750     0.671       898
weighted avg      0.808     0.687     0.705       898

After tuning, XGBoost achieved the lowest cost: 421.
This makes XGBoost the model choice.

In [ ]:
# Threshold tuning for XGBoost
for threshold in [0.2, 0.25, 0.3, 0.35, 0.4]:
  y_pred = proba > threshold
  print(f"Threshold: {threshold}")
  print(f"Precision: {precision_score(y_val, y_pred, pos_label=1)}")
  print(f"Recall: {recall_score(y_val, y_pred, pos_label=1)}")
  print(f"Cost: {business_cost(y_val, y_pred)}")
  print("\n")

Threshold: 0.2
Precision: 0.40262172284644193
Recall: 0.9033613445378151
Cost: 693.8913857677904


Threshold: 0.25
Precision: 0.4306122448979592
Recall: 0.8865546218487395
Cost: 537.9387755102041


Threshold: 0.3
Precision: 0.4535637149028078
Recall: 0.8823529411764706
Cost: 421.0


Threshold: 0.35
Precision: 0.468384074941452
Recall: 0.8403361344537815
Cost: 455.0


Threshold: 0.4
Precision: 0.4849246231155779
Recall: 0.8109243697478992
Cost: 475.0

### Experiment Tracking

In [ ]:
# Force MLflow to always use the project root's mlruns folder
project_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
mlflow.set_tracking_uri(f"file://{project_root}/mlruns")
mlflow.set_experiment("Telco Churn - XGBoost")

with mlflow.start_run():
    # Calculate scale_pos_weight
    scale_pos_weight = (y_train == 0).sum() / (y_train == 1).sum()

    # Best params from Optuna
    best_params = study.best_params
    best_params.update({
        "random_state": 42,
        "n_jobs": -1,
        "scale_pos_weight": scale_pos_weight,
        "eval_metric": "logloss"
    })

    # Log parameters
    mlflow.log_params(best_params)

    xgb = XGBClassifier(**best_params)
    xgb.fit(X_train, y_train)

    proba = xgb.predict_proba(X_test)[:, 1]
    y_pred = (proba >= THRESHOLD).astype(int)

    precision = precision_score(y_test, y_pred, pos_label=1)
    recall = recall_score(y_test, y_pred, pos_label=1)
    cost = business_cost(y_test, y_pred)

    # Log metrics
    mlflow.log_metric("precision", precision)
    mlflow.log_metric("recall", recall)
    mlflow.log_metric("cost", cost)

    # Save model
    mlflow.xgboost.log_model(xgb, "model")

    print(f"Cost: {cost}\n")
    print(classification_report(y_test, y_pred))

2026/09/09 21:53:28 INFO mlflow.tracking.fluent: Experiment with name 'Telco Churn - XGBoost' does not exist. Creating a new experiment.
2026/09/09 21:53:31 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

Cost: 476.0

              precision    recall  f1-score   support

           0       0.94      0.62      0.75       777
           1       0.46      0.89      0.61       280

    accuracy                           0.69      1057
   macro avg       0.70      0.76      0.68      1057
weighted avg       0.81      0.69      0.71      1057